### ISSUE TITLE
python 3.9 support

### ISSUE THREAD

**Issue by laukhin** [laukhin/asyncpgx#9]
Should be easy enough from our side, but i'm not sure if asyncpg supports 3.9 already. Need to check it and update the pyproject.toml and CI.

**Comment by franklx** [comment]
asyncpg supports python 3.9 from 0.22 and python 3.10 from 0.24 .
i'm using asyncpgx 1.1.1 and asyncpg 0.23 in production even the version published depends on 0.21;
will you release version 1.1.2 with dependency from latest asyncpg (0.23, 0.24)?

**Comment by laukhin** [comment]
@franklx thanks for noticing! Done, i've released 1.1.2 version with asyncpg 0.24 support.
